# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

# Welcome to Colab!
"""

import pandas as pd

df = pd.read_csv('raw-dataset.csv')
print("Rows:", len(df))
print("Columns:", len(df.columns))
df.head()

# Documented exclusion: this participant's justifications showed clear
# evidence of consulting an external AI chatbot live during the study
# (e.g. copy-pasted dialogue like "give me the survey AI recommendation
# after this"), which is inconsistent with the study design of presenting
# a single predefined AI recommendation. All 7 of their task responses
# are excluded from analysis.
excluded_participant_ids = ['4b9cfb04-e24f-452d-83f1-5fecc0d232bf']

rows_before = len(df)
df = df[~df['participantId'].isin(excluded_participant_ids)].reset_index(drop=True)
rows_after = len(df)

print(f"Excluded {rows_before - rows_after} rows ({len(excluded_participant_ids)} participant(s))")
print(f"Remaining: {rows_after} rows, {df['participantId'].nunique()} participants")

tasks_per_participant = df.groupby('participantId').size()

print("Distribution of task count per participant:")
print(tasks_per_participant.value_counts().sort_index())
print()
print("All participants have exactly 7 tasks:", (tasks_per_participant == 7).all())

missing = df.isna().sum()
missing = missing[missing > 0]

if len(missing) == 0:
    print("No missing values in the entire dataset.")
else:
    print(missing)

print("Overall AI condition distribution:")
print(df['aiCondition'].value_counts())
print()
print("As percentages:")
print(df['aiCondition'].value_counts(normalize=True).round(3) * 100)
print()

print("Balance per individual task (rows = task, columns = condition):")
condition_by_task = pd.crosstab(df['taskId'], df['aiCondition'])
print(condition_by_task)
print()

condition_by_task['max_deviation'] = condition_by_task.max(axis=1) - condition_by_task.min(axis=1)
print("Max deviation from perfectly equal split, per task:")
print(condition_by_task['max_deviation'])

print("How many times each position (1-7) appears overall:")
print(df['taskOrder'].value_counts().sort_index())
print()

print("Which task appears at which position (should look shuffled, not fixed):")
order_by_task = pd.crosstab(df['taskId'], df['taskOrder'])
print(order_by_task)

# Static study-design reference: which answer (0=A, 1=B, 2=C, 3=D) the AI
# recommends for each task, under each condition. This is fixed by the
# task design (from tasks.js) and is the same for every participant —
# it's not personal data, so it doesn't need to live in Firestore.
TASK_REFERENCE = {
    'inference-1':      {'correct': 1, 'incorrect': 0, 'partial': 3},
    'deduction-1':      {'correct': 1, 'incorrect': 0, 'partial': 3},
    'evaluation-1':     {'correct': 1, 'incorrect': 2, 'partial': 3},
    'probabilistic-1':  {'correct': 1, 'incorrect': 3, 'partial': 2},
    'evidence-1':       {'correct': 2, 'incorrect': 0, 'partial': 3},
    'evaluation-2':     {'correct': 0, 'incorrect': 3, 'partial': 2},
    'evidence-2':       {'correct': 1, 'incorrect': 0, 'partial': 3},
}

df['aiRecommendedAnswer'] = df.apply(
    lambda row: TASK_REFERENCE[row['taskId']][row['aiCondition']], axis=1
)

# Sanity check: for the 'correct' condition, the AI-recommended answer
# should always equal correctAnswer.
mismatch = df[(df['aiCondition'] == 'correct') & (df['aiRecommendedAnswer'] != df['correctAnswer'])]
assert mismatch.empty, f"Reference table mismatch on rows: {mismatch['taskId'].tolist()}"
print("Reference table check passed.")

bool_columns = ['initialCorrect', 'explanationViewed', 'finalCorrect', 'answerChanged']
for col in bool_columns:
    if df[col].dtype == object:
        df[col] = df[col].map({'True': True, 'False': False, True: True, False: False})

print(df[bool_columns].dtypes)

df['followedAI'] = df['finalAnswer'] == df['aiRecommendedAnswer']

df['changedTowardAI'] = (
    df['answerChanged']
    & (df['finalAnswer'] == df['aiRecommendedAnswer'])
    & (df['initialAnswer'] != df['aiRecommendedAnswer'])
)

df['harmfulChange'] = df['answerChanged'] & df['initialCorrect'] & ~df['finalCorrect']
df['beneficialChange'] = df['answerChanged'] & ~df['initialCorrect'] & df['finalCorrect']

df['correctnessChange'] = df['finalCorrect'].astype(int) - df['initialCorrect'].astype(int)

df['confidenceIncrease'] = df['confidenceShift'] > 0
df['confidenceDecrease'] = df['confidenceShift'] < 0

print("Done. New columns:")
print(['followedAI','changedTowardAI','harmfulChange','beneficialChange',
       'correctnessChange','confidenceIncrease','confidenceDecrease'])

df['failureToInspectExplanation'] = ~df['explanationViewed']

df['confidenceIncreaseAfterWrongAI'] = (
    df['confidenceIncrease']
    & df['aiCondition'].isin(['incorrect', 'partial'])
    & df['followedAI']
)

print("Done.")

df['strongOutsourcingEvidence'] = (
    df['initialCorrect']
    & (df['aiCondition'] == 'incorrect')
    & df['followedAI']
    & ~df['explanationViewed']
    & df['confidenceIncrease']
)

print("Cases matching the strong outsourcing evidence pattern:", df['strongOutsourcingEvidence'].sum())

def classify_pattern(row):
    if row['aiCondition'] == 'correct' and row['followedAI']:
        return 'correct AI accepted'
    if row['aiCondition'] == 'incorrect' and row['followedAI']:
        return 'incorrect AI accepted'
    if row['aiCondition'] == 'partial' and row['followedAI']:
        return 'partial AI accepted'
    if row['aiCondition'] in ('incorrect', 'partial') and not row['followedAI']:
        return 'incorrect/partial AI rejected'
    if row['aiCondition'] == 'correct' and not row['followedAI'] and not row['finalCorrect']:
        return 'correct AI rejected, still wrong'
    return 'other'

df['behaviourPattern'] = df.apply(classify_pattern, axis=1)
print(df['behaviourPattern'].value_counts())

df['overreliance'] = (
    df['followedAI']
    & df['aiCondition'].isin(['incorrect', 'partial'])
    & ~df['explanationViewed']
    & ~df['finalCorrect']
)

df['engagedWithExplanation'] = df['explanationViewed'] & df['followedAI']

df['resistedFlawedAI'] = df['aiCondition'].isin(['incorrect', 'partial']) & df['finalCorrect']

df['appropriateReliance'] = df['followedAI'] & (df['aiCondition'] == 'correct') & df['finalCorrect']

df['highConfidenceWrongFinal'] = (df['finalConfidence'] >= 4) & ~df['finalCorrect']

df['justificationLength'] = df['justification'].fillna('').apply(lambda s: len(str(s).split()))

print("Done. Overreliance cases:", df['overreliance'].sum())
print("Resisted flawed AI cases:", df['resistedFlawedAI'].sum())

checks = []

checks.append(('initialCorrect == (initialAnswer==correctAnswer)',
    (df['initialCorrect'] == (df['initialAnswer'] == df['correctAnswer'])).all()))

checks.append(('finalCorrect == (finalAnswer==correctAnswer)',
    (df['finalCorrect'] == (df['finalAnswer'] == df['correctAnswer'])).all()))

checks.append(('answerChanged == (initialAnswer != finalAnswer)',
    (df['answerChanged'] == (df['initialAnswer'] != df['finalAnswer'])).all()))

checks.append(('followedAI == (finalAnswer==aiRecommendedAnswer)',
    (df['followedAI'] == (df['finalAnswer'] == df['aiRecommendedAnswer'])).all()))

expected = df['answerChanged'] & df['followedAI'] & (df['initialAnswer'] != df['aiRecommendedAnswer'])
checks.append(('changedTowardAI logic', (df['changedTowardAI'] == expected).all()))

expected = df['answerChanged'] & df['initialCorrect'] & ~df['finalCorrect']
checks.append(('harmfulChange logic', (df['harmfulChange'] == expected).all()))

expected = df['answerChanged'] & ~df['initialCorrect'] & df['finalCorrect']
checks.append(('beneficialChange logic', (df['beneficialChange'] == expected).all()))

expected = df['finalCorrect'].astype(int) - df['initialCorrect'].astype(int)
checks.append(('correctnessChange logic', (df['correctnessChange'] == expected).all()))

expected = df['finalConfidence'] - df['initialConfidence']
checks.append(('confidenceShift == finalConfidence-initialConfidence', (df['confidenceShift'] == expected).all()))

checks.append(('confidenceIncrease logic', (df['confidenceIncrease'] == (df['confidenceShift'] > 0)).all()))
checks.append(('confidenceDecrease logic', (df['confidenceDecrease'] == (df['confidenceShift'] < 0)).all()))
checks.append(('failureToInspectExplanation == ~explanationViewed', (df['failureToInspectExplanation'] == ~df['explanationViewed']).all()))

expected = df['followedAI'] & df['aiCondition'].isin(['incorrect','partial']) & ~df['explanationViewed'] & ~df['finalCorrect']
checks.append(('overreliance logic', (df['overreliance'] == expected).all()))

expected = df['aiCondition'].isin(['incorrect','partial']) & df['finalCorrect']
checks.append(('resistedFlawedAI logic', (df['resistedFlawedAI'] == expected).all()))

expected = df['followedAI'] & (df['aiCondition']=='correct') & df['finalCorrect']
checks.append(('appropriateReliance logic', (df['appropriateReliance'] == expected).all()))

expected = (df['finalConfidence']>=4) & ~df['finalCorrect']
checks.append(('highConfidenceWrongFinal logic', (df['highConfidenceWrongFinal'] == expected).all()))

expected = df['initialCorrect'] & (df['aiCondition']=='incorrect') & df['followedAI'] & ~df['explanationViewed'] & df['confidenceIncrease']
checks.append(('strongOutsourcingEvidence logic', (df['strongOutsourcingEvidence'] == expected).all()))

for name, result in checks:
    status = "OK" if result else "!!! ERROR !!!"
    print(f"{status:15} {name}")

print("timeSpent (seconds) — summary:")
print(df['timeSpent'].describe())
print()

print("Rows with timeSpent > 600s (10+ min on a single task):", (df['timeSpent'] > 600).sum())
print("Rows with timeSpent > 1800s (30+ min):", (df['timeSpent'] > 1800).sum())
print()

print("Duplicate participantId+taskId rows:", df.duplicated(subset=['participantId','taskId']).sum())

justification_scores = pd.read_csv('justification-scores.csv')
print("Loaded:", len(justification_scores), "rows")
print("Score distribution:")
print(justification_scores['justificationScore'].value_counts().sort_index())

df = df.merge(
    justification_scores[['participantId', 'taskId', 'justificationScore']],
    on=['participantId', 'taskId'],
    how='left'
)

print("Rows after merge:", len(df))
print("Rows with a justificationScore:", df['justificationScore'].notna().sum())

low_quality_count = df.groupby('participantId')['justificationScore'].apply(lambda s: (s == 0).sum())
suspicious = low_quality_count[low_quality_count >= 5]

print("Participants with 5+ out of 7 tasks scored 0 (no meaningful justification):", len(suspicious))
print()
print("Participants with all 7 tasks scored 0:", (low_quality_count == 7).sum())

# Flag participants for sensitivity analysis, rather than deleting them —
# they still have valid task responses, just weak/absent justifications.
low_effort_ids = low_quality_count[low_quality_count >= 5].index
df['lowEngagementParticipant'] = df['participantId'].isin(low_effort_ids)

# Same approach for the extreme timeSpent outliers — flag, don't delete.
df['timeOutlier'] = df['timeSpent'] > 600

print("Rows flagged as low engagement:", df['lowEngagementParticipant'].sum())
print("Rows flagged as time outlier:", df['timeOutlier'].sum())

print("Age group:")
print(df.drop_duplicates('participantId')['ageGroup'].value_counts())
print()

print("Education level:")
print(df.drop_duplicates('participantId')['educationLevel'].value_counts())
print()

print("AI use frequency:")
print(df.drop_duplicates('participantId')['aiUseFrequency'].value_counts())
print()

print("Self-rated AI literacy:")
print(df.drop_duplicates('participantId')['selfRatedAI'].value_counts())
print()

print("Trust in AI (1-5 scale) — summary:")
print(df.drop_duplicates('participantId')['trustInAI'].describe())
print()

print("AI dependence (1-5 scale) — summary:")
print(df.drop_duplicates('participantId')['aiDependence'].describe())

import matplotlib.pyplot as plt

participants = df.drop_duplicates('participantId')

fig, axes = plt.subplots(2, 3, figsize=(16, 9))

participants['ageGroup'].value_counts().sort_index().plot(kind='bar', ax=axes[0,0], title='Age group')
participants['educationLevel'].value_counts().plot(kind='bar', ax=axes[0,1], title='Education level')
participants['aiUseFrequency'].value_counts().plot(kind='bar', ax=axes[0,2], title='AI use frequency')
participants['selfRatedAI'].value_counts().plot(kind='bar', ax=axes[1,0], title='Self-rated AI literacy')
participants['trustInAI'].value_counts().sort_index().plot(kind='bar', ax=axes[1,1], title='Trust in AI (1-5)')
participants['aiDependence'].value_counts().sort_index().plot(kind='bar', ax=axes[1,2], title='AI dependence (1-5)')

for ax in axes.flat:
    ax.tick_params(axis='x', rotation=45)
    ax.set_ylabel('Number of participants')

plt.tight_layout()
plt.show()

initial_accuracy = df.groupby('taskId')['initialCorrect'].mean().sort_values()
print("Initial accuracy rate per task (before seeing AI):")
print((initial_accuracy * 100).round(1))

import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(9, 5))
initial_accuracy.plot(kind='barh', ax=ax, color='#4C72B0')
ax.set_xlabel('Proportion initially correct')
ax.set_title('Initial (pre-AI) accuracy rate per task')
ax.axvline(0.5, color='gray', linestyle='--', linewidth=1)
plt.tight_layout()
plt.show()

baseline_confidence = df.groupby('aiCondition')['initialConfidence'].agg(['mean', 'std', 'count'])
print(baseline_confidence.round(2))

fig, ax = plt.subplots(figsize=(7, 5))
df.boxplot(column='initialConfidence', by='aiCondition', ax=ax)
ax.set_title('Initial confidence by AI condition (should look similar)')
ax.set_ylabel('Initial confidence (1-5)')
plt.suptitle('')
plt.tight_layout()
plt.show()

primary_vars = ['changedTowardAI', 'harmfulChange', 'overreliance', 'resistedFlawedAI', 'strongOutsourcingEvidence']

print("=== Overview across all 826 observations ===")
for var in primary_vars:
    count = df[var].sum()
    pct = df[var].mean() * 100
    print(f"{var:28} {count:4} cases  ({pct:.1f}%)")

print()
print("=== Confidence shift — overall ===")
print(df['confidenceShift'].describe().round(2))

flawed_rows = df[df['aiCondition'].isin(['incorrect', 'partial'])]
print(f"Rows with a flawed (incorrect/partial) recommendation: {len(flawed_rows)}")
print(f"Of those, resisted (stayed/reached correct): {flawed_rows['resistedFlawedAI'].sum()} ({flawed_rows['resistedFlawedAI'].mean()*100:.1f}%)")
print(f"Of those, overreliance cases: {flawed_rows['overreliance'].sum()} ({flawed_rows['overreliance'].mean()*100:.1f}%)")
print(f"Of those, harmfulChange cases: {flawed_rows['harmfulChange'].sum()} ({flawed_rows['harmfulChange'].mean()*100:.1f}%)")

import matplotlib.pyplot as plt

labels = ['Resisted\nflawed AI', 'Overreliance', 'Harmful\nchange']
values = [
    flawed_rows['resistedFlawedAI'].mean()*100,
    flawed_rows['overreliance'].mean()*100,
    flawed_rows['harmfulChange'].mean()*100
]

fig, ax = plt.subplots(figsize=(7,5))
bars = ax.bar(labels, values, color=['#55A868','#C44E52','#8172B2'])
ax.set_ylabel('% of observations with a flawed (incorrect/partial) AI recommendation')
ax.set_title('Response to flawed AI recommendations (n=550)')
for bar, val in zip(bars, values):
    ax.text(bar.get_x()+bar.get_width()/2, val+1, f'{val:.1f}%', ha='center')
plt.tight_layout()
plt.show()

confidence_by_condition = df.groupby('aiCondition')['confidenceShift'].agg(['mean', 'std', 'count']).round(2)
print(confidence_by_condition)
print()

print("Confidence shift when AI was followed vs not, by condition:")
print(df.groupby(['aiCondition', 'followedAI'])['confidenceShift'].mean().round(2))

import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(8,5))
df.groupby('aiCondition')['confidenceShift'].mean().plot(kind='bar', ax=ax, color=['#55A868','#C44E52','#DD8452'])
ax.set_ylabel('Mean confidence shift (final - initial)')
ax.set_title('Mean confidence shift by AI condition')
ax.axhline(0, color='black', linewidth=0.8)
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

pivot = df.groupby(['aiCondition', 'followedAI'])['confidenceShift'].mean().unstack()
pivot = pivot.reindex(['correct', 'incorrect', 'partial'])

fig, ax = plt.subplots(figsize=(9,5))
x = np.arange(len(pivot.index))
width = 0.35

ax.bar(x - width/2, pivot[False], width, label='Did not follow AI', color='#4C72B0')
ax.bar(x + width/2, pivot[True], width, label='Followed AI', color='#C44E52')

ax.set_xticks(x)
ax.set_xticklabels(pivot.index)
ax.set_ylabel('Mean confidence shift')
ax.set_title('Confidence shift by condition and whether AI was followed')
ax.axhline(0, color='black', linewidth=0.8)
ax.legend()
plt.tight_layout()
plt.show()

print("Mean justificationScore by AI condition:")
print(df.groupby('aiCondition')['justificationScore'].mean().round(2))
print()

print("Mean justificationScore: overreliance vs not:")
print(df.groupby('overreliance')['justificationScore'].mean().round(2))
print()

print("Mean justificationScore: followedAI vs not (within flawed conditions only):")
print(flawed_rows.groupby('followedAI')['justificationScore'].mean().round(2))

import matplotlib.pyplot as plt

fig, axes = plt.subplots(1, 2, figsize=(13,5))

df.groupby('aiCondition')['justificationScore'].mean().plot(kind='bar', ax=axes[0], color=['#55A868','#C44E52','#DD8452'])
axes[0].set_title('Mean justification score by AI condition')
axes[0].set_ylabel('Mean score (0-3)')
axes[0].tick_params(axis='x', rotation=0)

df.groupby('overreliance')['justificationScore'].mean().plot(kind='bar', ax=axes[1], color=['#4C72B0','#C44E52'])
axes[1].set_title('Mean justification score: overreliance vs not')
axes[1].set_xticklabels(['Not overreliance', 'Overreliance'], rotation=0)
axes[1].set_ylabel('Mean score (0-3)')

plt.tight_layout()
plt.show()

from scipy.stats import chi2_contingency

contingency = pd.crosstab(df['aiCondition'], df['followedAI'])
print(contingency)
print()

chi2, p, dof, expected = chi2_contingency(contingency)
print(f"Chi-square = {chi2:.2f}, df = {dof}, p-value = {p:.10f}")

# For each participant, compute their followedAI rate separately for
# each condition they encountered (repeated-measures structure: same
# participant contributes to all 3 conditions, just via different tasks).
participant_rates = df.groupby(['participantId', 'aiCondition'])['followedAI'].mean().unstack()
print(participant_rates.head())
print()
print("Participants with data in all 3 conditions:", participant_rates.dropna().shape[0], "out of", len(participant_rates))

from scipy.stats import friedmanchisquare

friedman_stat, friedman_p = friedmanchisquare(
    participant_rates['correct'],
    participant_rates['incorrect'],
    participant_rates['partial']
)
print(f"Friedman chi-square = {friedman_stat:.2f}, p-value = {friedman_p:.10f}")
print()

print("Mean followedAI rate per participant, by condition:")
print(participant_rates.mean().round(3))

from scipy.stats import wilcoxon

pairs = [('correct', 'incorrect'), ('correct', 'partial'), ('incorrect', 'partial')]

for a, b in pairs:
    stat, p = wilcoxon(participant_rates[a], participant_rates[b])
    print(f"{a} vs {b}: W = {stat:.1f}, p = {p:.8f}")

import numpy as np

# Kendall's W for the Friedman test: W = chi-square / (n * (k-1))
n_participants = len(participant_rates)
k_conditions = 3
kendalls_w = friedman_stat / (n_participants * (k_conditions - 1))
print(f"Kendall's W = {kendalls_w:.3f}  (n={n_participants}, k={k_conditions})")
print("Interpretation guide: ~0.1 small, ~0.3 medium, ~0.5+ large")
print()

# Matched-pairs rank-biserial correlation for each Wilcoxon comparison:
# r = 1 - (2*T) / (n*(n+1)), where T is the smaller rank sum (the
# statistic scipy's wilcoxon returns by default) and n is the number
# of non-zero differences in that pair.
def rank_biserial(a, b):
    diff = a - b
    n_nonzero = (diff != 0).sum()
    stat, p = wilcoxon(a, b)
    r = 1 - (2 * stat) / (n_nonzero * (n_nonzero + 1))
    return stat, p, r, n_nonzero

for cond_a, cond_b in pairs:
    stat, p, r, n_nz = rank_biserial(participant_rates[cond_a], participant_rates[cond_b])
    print(f"{cond_a} vs {cond_b}: W={stat:.1f}, p={p:.8f}, rank-biserial r={r:.3f} (n_nonzero={n_nz})")

# Sensitivity check: same Friedman test, excluding low-engagement participants
df_clean = df[~df['lowEngagementParticipant']]
print(f"Participants remaining: {df_clean['participantId'].nunique()} (excluded {df['participantId'].nunique() - df_clean['participantId'].nunique()})")
print()

participant_rates_clean = df_clean.groupby(['participantId', 'aiCondition'])['followedAI'].mean().unstack()

from scipy.stats import friedmanchisquare
friedman_stat_clean, friedman_p_clean = friedmanchisquare(
    participant_rates_clean['correct'],
    participant_rates_clean['incorrect'],
    participant_rates_clean['partial']
)
print(f"Friedman chi-square (excl. low engagement) = {friedman_stat_clean:.2f}, p-value = {friedman_p_clean:.10f}")
print()
print("Mean followedAI rate per participant, by condition (excl. low engagement):")
print(participant_rates_clean.mean().round(3))

# Sensitivity check #2: same Friedman test, excluding time outlier rows
df_no_outliers = df[~df['timeOutlier']]
print(f"Rows remaining: {len(df_no_outliers)} (excluded {len(df) - len(df_no_outliers)})")
print(f"Participants remaining: {df_no_outliers['participantId'].nunique()}")
print()

participant_rates_no_outliers = df_no_outliers.groupby(['participantId', 'aiCondition'])['followedAI'].mean()
participant_rates_no_outliers = participant_rates_no_outliers.unstack()

# Some participants might now be missing a condition entirely if their
# only task in that condition was the outlier row — check for that first.
missing = participant_rates_no_outliers[participant_rates_no_outliers.isna().any(axis=1)]
print(f"Participants now missing a full condition: {len(missing)}")

participant_rates_no_outliers_complete = participant_rates_no_outliers.dropna()

from scipy.stats import friedmanchisquare
friedman_stat_2, friedman_p_2 = friedmanchisquare(
    participant_rates_no_outliers_complete['correct'],
    participant_rates_no_outliers_complete['incorrect'],
    participant_rates_no_outliers_complete['partial']
)
print(f"Friedman chi-square (excl. time outliers) = {friedman_stat_2:.2f}, p-value = {friedman_p_2:.10f}")
print()
print("Mean followedAI rate per participant, by condition (excl. time outliers):")
print(participant_rates_no_outliers_complete.mean().round(3))

participant_summary = df.groupby('participantId').agg(
    followedAI_rate=('followedAI', 'mean'),
    aiUseFrequency=('aiUseFrequency', 'first'),
    selfRatedAI=('selfRatedAI', 'first'),
    trustInAI=('trustInAI', 'first'),
    aiDependence=('aiDependence', 'first'),
).reset_index()

# Overreliance rate only makes sense within flawed (incorrect/partial) trials
flawed_only = df[df['aiCondition'].isin(['incorrect', 'partial'])]
overreliance_rate = flawed_only.groupby('participantId')['overreliance'].mean().rename('overreliance_rate')

participant_summary = participant_summary.merge(overreliance_rate, on='participantId', how='left')

print(participant_summary.head())
print()
print(participant_summary.describe(include='all'))

print("Unique values in aiUseFrequency:")
print(df['aiUseFrequency'].value_counts())
print()
print("Unique values in selfRatedAI:")
print(df['selfRatedAI'].value_counts())

# Fix browser-translation artifacts: a few participants' browsers
# auto-translated the page before submission, capturing translated
# dropdown text instead of the original English value. Clear
# translations are recoded; "Tılımlı" has no standard meaning and is
# left as unknown rather than guessed.
translation_map_freq = {
    '每日报': 'Daily',
    'Diário': 'Daily',
    '毎日': 'Daily',
    'Aylık': 'Monthly',
}
translation_map_literacy = {
    '中等': 'Moderate',
    'Alto': 'High',
    '高い': 'High',
    'Tılımlı': pd.NA,  # meaning unclear, left as unknown rather than guessed
}

df['aiUseFrequency'] = df['aiUseFrequency'].replace(translation_map_freq)
df['selfRatedAI'] = df['selfRatedAI'].replace(translation_map_literacy)

print("aiUseFrequency after cleanup:")
print(df['aiUseFrequency'].value_counts(dropna=False))
print()
print("selfRatedAI after cleanup:")
print(df['selfRatedAI'].value_counts(dropna=False))

participant_summary = df.groupby('participantId').agg(
    followedAI_rate=('followedAI', 'mean'),
    aiUseFrequency=('aiUseFrequency', 'first'),
    selfRatedAI=('selfRatedAI', 'first'),
    trustInAI=('trustInAI', 'first'),
    aiDependence=('aiDependence', 'first'),
).reset_index()

flawed_only = df[df['aiCondition'].isin(['incorrect', 'partial'])]
overreliance_rate = flawed_only.groupby('participantId')['overreliance'].mean().rename('overreliance_rate')
participant_summary = participant_summary.merge(overreliance_rate, on='participantId', how='left')

print(participant_summary.shape)
print(participant_summary['selfRatedAI'].value_counts(dropna=False))

print("Mean overreliance rate by AI use frequency:")
print(participant_summary.groupby('aiUseFrequency')['overreliance_rate'].agg(['mean', 'count']).round(3))
print()

print("Mean overreliance rate by self-rated AI literacy:")
print(participant_summary.groupby('selfRatedAI')['overreliance_rate'].agg(['mean', 'count']).round(3))

import matplotlib.pyplot as plt

fig, axes = plt.subplots(1, 2, figsize=(14,5))

order_freq = ['Never', 'Less than monthly', 'Monthly', 'Weekly', 'Daily']
participant_summary.groupby('aiUseFrequency')['overreliance_rate'].mean().reindex(order_freq).plot(kind='bar', ax=axes[0], color='#4C72B0')
axes[0].set_title('Mean overreliance rate by AI use frequency')
axes[0].set_ylabel('Overreliance rate')
axes[0].tick_params(axis='x', rotation=45)

order_lit = ['Very low', 'Low', 'Moderate', 'High', 'Very high']
participant_summary.groupby('selfRatedAI')['overreliance_rate'].mean().reindex(order_lit).plot(kind='bar', ax=axes[1], color='#C44E52')
axes[1].set_title('Mean overreliance rate by self-rated AI literacy')
axes[1].set_ylabel('Overreliance rate')
axes[1].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()

print("Correlation between overreliance_rate and trustInAI / aiDependence:")
print(participant_summary[['overreliance_rate', 'trustInAI', 'aiDependence']].corr().round(3))

from scipy.stats import spearmanr

r_trust, p_trust = spearmanr(participant_summary['trustInAI'], participant_summary['overreliance_rate'])
r_dep, p_dep = spearmanr(participant_summary['aiDependence'], participant_summary['overreliance_rate'])

print(f"Trust in AI vs overreliance:      Spearman r = {r_trust:.3f}, p = {p_trust:.4f}")
print(f"AI dependence vs overreliance:    Spearman r = {r_dep:.3f}, p = {p_dep:.4f}")

print("harmfulChange rate by task (within flawed-condition trials only):")
harmful_by_task = flawed_only.groupby('taskId')['harmfulChange'].agg(['sum', 'mean', 'count']).sort_values('mean', ascending=False)
print(harmful_by_task.round(3))
print()

print("What % of all harmfulChange cases come from each task:")
print((flawed_only.groupby('taskId')['harmfulChange'].sum() / flawed_only['harmfulChange'].sum() * 100).round(1).sort_values(ascending=False))
print()

print("overreliance rate by task (within flawed-condition trials only):")
overreliance_by_task = flawed_only.groupby('taskId')['overreliance'].agg(['sum', 'mean', 'count']).sort_values('mean', ascending=False)
print(overreliance_by_task.round(3))

import matplotlib.pyplot as plt

fig, axes = plt.subplots(1, 2, figsize=(14,5))

harmful_by_task['mean'].sort_values().plot(kind='barh', ax=axes[0], color='#C44E52')
axes[0].set_title('Harmful change rate by task')
axes[0].set_xlabel('Rate (within flawed-condition trials)')

overreliance_by_task['mean'].sort_values().plot(kind='barh', ax=axes[1], color='#8172B2')
axes[1].set_title('Overreliance rate by task')
axes[1].set_xlabel('Rate (within flawed-condition trials)')

plt.tight_layout()
plt.show()

overreliance_justifications = df[df['overreliance'] == True]['justification']
resistance_justifications = df[df['resistedFlawedAI'] == True]['justification']

print(f"Overreliance justifications: {len(overreliance_justifications)}")
print(f"Resistance justifications: {len(resistance_justifications)}")
print()

print("=== Sample of 15 resistance justifications ===")
for text in resistance_justifications.sample(25, random_state=7):
   print("-", text)

resistance_quality = df[df['resistedFlawedAI']]['justificationScore'].value_counts(normalize=True).sort_index() * 100
print("Justification score distribution WITHIN resistedFlawedAI cases:")
print(resistance_quality.round(1))
print()

overreliance_quality = df[df['overreliance']]['justificationScore'].value_counts(normalize=True).sort_index() * 100
print("Justification score distribution WITHIN overreliance cases:")
print(overreliance_quality.round(1))